<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Form1.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Form1.Designer.cs">
      <DependentUpon>Form1.cs</DependentUpon>
    </Compile>
    <Compile Include="Forms\LoginForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Forms\LoginForm.Designer.cs">
      <DependentUpon>LoginForm.cs</DependentUpon>
    </Compile>
    <Compile Include="Forms\MangeUserForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Forms\MangeUserForm.Designer.cs">
      <DependentUpon>MangeUserForm.cs</DependentUpon>
    </Compile>
    <Compile Include="Forms\ManageRestaurantsForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Forms\ManageRestaurantsForm.Designer.cs">
      <DependentUpon>ManageRestaurantsForm.cs</DependentUpon>
    </Compile>
    <Compile Include="Helpers\DBHelper.cs" />
    <Compile Include="Models\User.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="Repositories\UserRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Update="App.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
